# Setup
title:               Flaming heap of nonesense
#tagline:            'Musings'
description:         'Tharr be some good pages here.'
url:                 http://irvinalcaraz.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Irvin Alcaraz
  email:             alcarazirvin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
